name: Check Latest Pull

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch --prune --unshallow

      - name: Check pull request branch
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          git merge-base --is-ancestor ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
          if [ $? -eq 0 ]; then
            echo "Pull request branch is up to date with the base branch."
          else
            echo "Pull request branch is behind the base branch."
            exit 1
          fi

